from typing import Any, Protocol


class InvestigationStorageInterface(Protocol):
    def save_observation(
        self, observation_data: dict[str, Any], session_id: str
    ) -> str: ...

    def save_question(self, question_data: dict[str, Any], session_id: str) -> str: ...

    def save_pattern(self, pattern_data: dict[str, Any], session_id: str) -> str: ...

    def save_session(self, session_data: dict[str, Any]) -> str: ...

    def verify_storage_integrity(self) -> dict[str, Any]: ...

    def prepare_for_large_run(self, file_count: int) -> dict[str, Any]: ...
