from typing import Any, Dict, Protocol


class InvestigationStorageInterface(Protocol):
    def save_observation(self, observation_data: Dict[str, Any], session_id: str) -> str: ...

    def save_question(self, question_data: Dict[str, Any], session_id: str) -> str: ...

    def save_pattern(self, pattern_data: Dict[str, Any], session_id: str) -> str: ...

    def save_session(self, session_data: Dict[str, Any]) -> str: ...

    def verify_storage_integrity(self) -> Dict[str, Any]: ...

    def prepare_for_large_run(self, file_count: int) -> Dict[str, Any]: ...
